# Generated by Django 3.2.6 on 2021-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
